local custom_opts = {
  hidden = true,
  number = true,
  relativenumber = true,
  ttimeout = false,
  list = true,
  ignorecase = true,
  smartcase = true,
  expandtab = true,
  undofile = true,
  backup = false,
  swapfile = false,
  writebackup = false,
  hlsearch = false,
  wrap = false,
  timeout = false,
  joinspaces = false,
  showmode = false,
  -- guicursor = '',
  signcolumn = 'yes',
  ttimeoutlen = 0,
  scrolloff = 64,
  sidescrolloff = 5,
  inccommand = 'nosplit',
  conceallevel = 0,
  showtabline = 1,
  sw = 2,
  tw = 0,
  laststatus = 3,
  splitright = true,
  splitbelow = true,
  indentexpr = "",
  smartindent = false,
  cindent = false,
  autoindent = true,
  list = true,
  listchars = 'tab:⇥ ,space:·,eol:↲',
}

for opt, value in pairs(custom_opts) do
  vim.opt[opt] = value
end
