require('nvim-treesitter.configs').setup {
  autotag = {
    enable = true,
  },

  auto_install = true,
  ensure_installed = {
    'bash',
    'bibtex',
    'c',
    'cmake',
    'comment',
    'cpp',
    'css',
    'csv',
    'diff',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'gotmpl',
    'gowork',
    'gpg',
    'html',
    'htmldjango',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'json5',
    'jsonc',
    'kconfig',
    'latex',
    'ledger',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'markdown_inline',
    'objdump',
    'passwd',
    'pem',
    'php',
    'php_only',
    'phpdoc',
    'prisma',
    'pymanifest',
    'python',
    'r',
    'readline',
    'requirements',
    'rust',
    --'scheme' -- not ready
    'sql',
    'ssh_config',
    'strace',
    'terraform',
    'tmux',
    'toml',
    'tsv',
    'tsx',
    'typescript',
    'udev',
    'verilog',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
  },
  sync_install = false,

  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },

  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = "grn",
      scope_incremental = "grc",
      node_decremental = "grm",
    },
  },

  textobjects = {
    select = {
      enable = true,
      keymaps = {
        -- You can use the capture groups defined in textobjects.scm
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
      },
    },
  },

  -- indent = { enable = true }, -- doesn't indent properly, but still better than
  --                             -- installing plugins for filetypes, which use regexes.
}
